name: knowyourfan
description: "Projeto desenvolvido para teste tecnico da furia!"

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  provider:
  go_router:
  image_picker:
  http:
  qr_flutter:
  flutter_dotenv:

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:

  assets:
    - .env
    - assets/images/


  uses-material-design: true
